Vagrant.configure("2") do |config|

  NodeCount = 2

  (1..NodeCount).each do |i|
      config.vm.define "ubuntu-worker0#{i}" do |node|
          node.vm.box = "generic/ubuntu2204"
          node.vm.hostname = "ubuntu-worker0#{i}"
          node.vm.network "private_network"
          node.vm.synced_folder "./sync", "/sync"
          node.vm.provider "hyperv" do |hyperv|
              hyperv.vmname = "ubuntu-worker0#{i}"
              hyperv.memory = 1024
              hyperv.cpus = 1
          end
      end
  end


  config.vm.define "ubuntu-control" do |control|
      control.vm.box = "generic/ubuntu2204"
      control.vm.hostname = "ubuntu-control"
      control.vm.network "private_network"
      control.vm.synced_folder "./sync", "/sync"
      control.vm.provider "hyperv" do |hyperv|
          hyperv.vmname = "ubuntu-control"
          hyperv.memory = 1024
          hyperv.cpus = 2
      end
  end
end